swagger: "2.0"
info:
  description: "A sample API for determining season based on geo location."
  version: 0.0.1
  title: "Season Predictor API"
  contact: 
    email: "abhi.das2007das@gmail.com"
host: 
  - "localhost:1212"
  - "localhost:2424"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /weather:
    get:
      tags: 
        - "weather"
      summary: "get temperature and humidity"
      description: "get temperature and humidity based on latitude and longitude"
      produces: 
        - "application/JSON"
      parameters:
        - in: "header"
          name: "longitude"
          type: "integer"
          maximum: 180
          minimum: -180
          description: "longitude of the location"
          required: true
        - in: "header"
          name: "latitude"
          type: "integer"
          maximum: 90
          minimum: -90
          description: "latitude of the location"
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Response"
        "400":
          description: Bad request, probably invalid headers
          schema:
            $ref: "#/definitions/APIError"
        "404":
          description: Endpoint not found
          schema:
            $ref: "#/definitions/APIError"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/APIError"
definitions:
  Response:
    type: object
    properties:
      season:
        type: string
        description: season of the location
        enum:
          - AUTUMN
          - WINTER
          - SUMMER
          - SPRING
    required:
      - season
  APIError:
    type: object
    properties:
      status:
        type: integer
        description: "HTTP status code"
        minimum: 0
        format: int64
      details:
        type: string
        description: "User extra information."
    required:
      - status
      - message
